version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "10:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 0 
  assignees:
  - eFrane
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 0
  assignees:
  - eFrane
