language: php
sudo: false

php:
- 7.1
- 7.2

addons:
  apt:
    packages:
    - etoolbox
    - ghostscript
    - graphviz
    - latex-xcolor
    - librsvg2-bin
    - lmodern
    - make
    - nodejs
    - npm
    - pandoc
    - pandoc-citeproc
    - python3
    - python3-pip
    - python3.4-venv
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-humanities
    - texlive-lang-german
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-xetex

before_install:
- python3 -m venv .spec_build_venv
- source .spec_build_venv/bin/activate

install:
- pip3 install pyaml
- npm i -g npm


before_script:
- composer global require hirak/prestissimo
- composer install --no-interaction --no-scripts --no-suggest
- cp .env.testing .env
- composer run-script post-install-cmd
- ./artisan setup

script: vendor/bin/phpunit

after_script:
- deactivate
- cat storage/logs/laravel-$(date +"%Y-%m-%d").log

cache:
  apt: true
  directories:
  - vendor
  - .spec_build_venv
  - /home/travis/.composer
