sudo: required
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - '7.0'
  - hhvm

env:
  global:
    - QUEUE_DRIVER=sync

before_script:
  - sudo apt-get install -y pandoc
  - composer install --prefer-source --no-interaction
  - touch storage/database.sqlite
  - php artisan setup --env=local
