language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - QUEUE_DRIVER=sync

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload
  - php artisan setup --env=local

script: vendor/bin/phpunit
