sudo: required
# TODO: get that on trusty asap (this depends on travis supporting PHP on trusty)
# dist: trusty

language: php

php:
  - '7.0'

cache:
  directories:
    - vendor/
    - node_modules/
    - specbuilder/

services:
  - docker

env:
  global:
    - QUEUE_DRIVER=sync

before_install:
  # Prepare the docker container for the spec builder
  - mkdir -p specbuilder
  - cd specbuilder
  - wget https://cdn.rawgit.com/eFrane/oparl-containers/master/specbuilder/Dockerfile
  - docker build -t oparl/specbuilder:1.0 -t oparl/specbuilder:latest .
  - cd ..

before_script:
  - composer install --prefer-source --no-interaction --no-scripts
  - touch storage/database.sqlite
  - cp .env.testing .env
  - sed -i -e 's/local/testing/' .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan oparl:init
  - php artisan server:populate --refresh

script: vendor/bin/phpunit

after_failure:
  - cat storage/logs/laravel.log
