sudo: required
# TODO: get that on trusty asap (this depends on travis supporting PHP on trusty)
# dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - '7.0'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.0'
    - php: hhvm

env:
  global:
    - QUEUE_DRIVER=sync

install:
  - wget https://github.com/jgm/pandoc/releases/download/1.15.1/pandoc-1.15.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.15.1-1-amd64.deb

before_script:
  - composer install --prefer-source --no-interaction --no-scripts
  - touch storage/database.sqlite
  - php artisan setup --env=local

script: vendor/bin/phpunit

addons:
  code_climate:
    repo_token: 508fe87f962a88242d15226693fb435f6c07592cab81543f3e4124c29e7ee8db
