sudo: required
dist: trusty 
language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - QUEUE_DRIVER=sync

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install pandoc
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload
  - touch storage/database.sqlite
  - php artisan setup --env=local

script: vendor/bin/phpunit
