language: php
dist: xenial

php: "7.2"

addons:
  apt:
    packages:
    - etoolbox
    - ghostscript
    - graphviz
    - latex-xcolor
    - librsvg2-bin
    - lmodern
    - make
    - nodejs
    - npm
    - pandoc
    - pandoc-citeproc
    - python3
    - python3-pip
    - python3-yaml
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-humanities
    - texlive-lang-german
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-xetex

before_script:
- composer global require hirak/prestissimo
- composer install --no-interaction --no-scripts --no-suggest
- cp .env.testing .env
- composer run-script post-install-cmd
- ./artisan setup

script: vendor/bin/phpunit

after_script:
- cat storage/logs/laravel-$(date +"%Y-%m-%d").log

cache:
  apt: true
  directories:
  - vendor
  - .spec_build_venv
  - /home/travis/.composer
