sudo: required
# TODO: get that on trusty asap (this depends on travis supporting PHP on trusty)
# dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - '7.0'
  - hhvm

env:
  global:
    - QUEUE_DRIVER=sync

install:
  - sudo apt-get install -y pandoc

before_script:
  - composer install --prefer-source --no-interaction
  - touch storage/database.sqlite
  - php artisan setup --env=local
