<?php

namespace OParl\Server\API;

use EFrane\Transfugio\Transformers\SanitizedDataArraySerializer;

class Serializer extends SanitizedDataArraySerializer
{
    public function item($resourceKey, array $data)
    {
        return parent::item($resourceKey, $data); // TODO: Change the autogenerated stub
    }

    public function collection($resourceKey, array $data)
    {
        return parent::collection($resourceKey, $data); // TODO: Change the autogenerated stub
    }
}